// Code generated by "stringer -type=ButtonState"; DO NOT EDIT.

package streamdeck

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ButtonInvalid - -1]
	_ = x[ButtonReleased-0]
	_ = x[ButtonPressed-1]
}

const _ButtonState_name = "ButtonInvalidButtonReleasedButtonPressed"

var _ButtonState_index = [...]uint8{0, 13, 27, 40}

func (i ButtonState) String() string {
	i -= -1
	if i < 0 || i >= ButtonState(len(_ButtonState_index)-1) {
		return "ButtonState(" + strconv.FormatInt(int64(i+-1), 10) + ")"
	}
	return _ButtonState_name[_ButtonState_index[i]:_ButtonState_index[i+1]]
}
